import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { findTargetRecipes, normalizeAttribution, resolvePair, samePair } from '../public/embed/breed/widget.js';
const breeding={special:[{parentA:'a',parentB:'b',child:'special-child',status:'resolved'},{parentA:'x',parentB:'y',child:'uncertain-child',status:'unresolved'}],normal:[{parentA:'a',parentB:'b',child:'normal-child'},{parentA:'c',parentB:'d',child:'normal-child'},{parentA:'e',parentB:'f',child:'target'}]};
assert.equal(samePair({parentA:'a',parentB:'b'},'b','a'),true);
assert.deepEqual(resolvePair(breeding,'b','a'),{status:'MATCH',kind:'special',child:'special-child'});
assert.deepEqual(resolvePair(breeding,'x','y'),{status:'REVIEW_REQUIRED',reason:'unresolved_special_recipe'});
assert.deepEqual(resolvePair(breeding,'d','c'),{status:'MATCH',kind:'normal',child:'normal-child'});
assert.deepEqual(resolvePair(breeding,'missing','pair'),{status:'UNKNOWN'});
assert.equal(findTargetRecipes(breeding,'uncertain-child').length,0);
assert.equal(findTargetRecipes(breeding,'target')[0].kind,'normal');
assert.equal(normalizeAttribution('partner-01.example'),'partner-01.example');
assert.equal(normalizeAttribution('bad value'),null); assert.equal(normalizeAttribution('x'.repeat(65)),null);
const html=await readFile(new URL('../public/embed/breed/index.html',import.meta.url),'utf8');const js=await readFile(new URL('../public/embed/breed/widget.js',import.meta.url),'utf8');
assert.match(html,/id="widget"/);assert.match(html,/\.\/widget\.js/);for(const event of ['embed_loaded','breed_searched','pal_atlas_opened'])assert.match(js,new RegExp(event));assert.match(js,/非公式ファンプロジェクト/);assert.match(js,/\.\.\/\.\.\/api\/breeding\.json/);
console.log('embed contract tests passed');
